get:
  x-swagger-router-controller: "ApplicationsController"
  description: "Returns all Applications for the named Project."
  operationId: "ReadAllApplicationsByProjectSlug"
  summary: "Read all Applications by Project"
  consumes:
  - "application/json"
  produces:
  - "application/json"
  parameters:
  - name: "projectSlug"
    description: "The unique Project slug to search on."
    type: "string"
    in: "path"
    required: true
  - name: "detail"
    description: "Specifies the level of detail to return. Options are small, medium and full (default)."
    type: "string"
    in: "query"
  responses:
    200:
      description: "Success."
      schema:
        type: "object"
        additionalProperties:
          $ref: "../definitions/ApplicationObject.yaml"
    405:
      description: "Validation exception"
    500:
      description: "General failure"
    default:
      description: "Error"
post:
  x-swagger-router-controller: "ApplicationsController"
  description: "Create new Application object for the named Project object."
  operationId: "CreateApplicationByProjectSlug"
  summary: "Create Application by Project"
  consumes:
  - "application/json"
  produces:
  - "application/json"
  parameters:
  - name: "projectSlug"
    description: "The unique Project slug to search on."
    type: "string"
    in: "path"
    required: true
  - name: "body"
    description: "The Application object to create."
    schema:
      $ref: "../definitions/ApplicationObject.yaml"
    in: "body"
  - name: "detail"
    description: "Specifies the level of detail to return. Options are small, medium and full (default)."
    type: "string"
    in: "query"
  responses:
    200:
      description: "Success."
      schema:
        $ref: "../definitions/ApplicationObject.yaml"
    405:
      description: "Validation exception"
    default:
      description: "Error"
      schema:
        $ref: "../definitions/ErrorResponse.yaml"
