swagger: "2.0"
info:
  version: "0.1.0"
  title: "SJC Application Registry"
  description: "Registry as a Service providing daemon-like assistance to SJC CLI via HTTPS RESTful API."
  termsOfService: ""
  contact:
    name: "SJC"
  license:
    name: ""
host: "localhost:10010"
basePath: "/"
schemes:
- "http"
- "https"

consumes:
- "application/json"
produces:
- "application/json"
paths:

  ## All applications
  /applications:
    x-swagger-router-controller: "ApplicationsController"
    get:
      description: "Gets a list of all known applications"
      operationId: "ReadApplications"
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ApplicationResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"


          
definitions:

        
  ## Application Response Object ##        
  ApplicationResponse:
    description: "An Application Object including previously system generated UUID and ephemeralPort."
    type: "object"

    properties:
    
      name:
        type: "string"
        description: "The lowercase and dash-separated canonical name for this application."
        
      description:
        type: "string"
        description: "Unambiguously describes this specific SJC application."
      
      address: 
        type: "string"
        description: "The production/public domain."
        
      version:
        type: "string"
        description: "The SemVer version of the current instance of an SJC application. See [http://semver.org/](http://semver.org/)"
      
      bugs:
        type: "string"
        description: "The web address of the issue tracker."
        
      docs:
        type: "string"
        description: "The web address of the wiki or documentation repository."            
          
      branch:
        type: "string"
        description: "The repository branch name for a specific instance of this application"

        
      branches:
        type: "array"
        items:
          $ref: "#/definitions/BranchDefinition"
        

          
      cnames:
        type: "array"
        description: "List of cnames used to access this instance"
        items:
          $ref: "#/definitions/CNameDefinition"
        
      host:
        type: "string"
        description: "The host environment currently expected to be localhost or AWS."
        



      ephemeralPort:
        type: "string"
        format: "int32"
        

      healthCheck:
        type: "string"
        description: "Placeholder while we expand the idea of a heartbeat-like feature."
        format: "uri"
        

      remotes:
        type: "object"
        description: "Git repositories."
        additionalProperties:
          $ref: "#/definitions/GitRemote"

      testRunners:
        type: "object"
        description: "A list of available test runners that can be invoked within a running application instance."
        additionalProperties:
          $ref: "#/definitions/TestRunnerDefinition"


      tags:
        type: "array"
        items: 
          type: "string"

      commands:
        type: "object"
        description: "Zero, one or more shell commands."
        
        $ref: "#/definitions/CommandDefinition"

      services:
        type: "object"
        description: "For now, a wrapper around Docker file."
        additionalProperties:
          $ref: "#/definitions/ServiceDefinition"


      audit:
        type: "object"
        description: "A standard SJC audit object for tracking updates to each instance of an AppDef."
        $ref: "#/definitions/AuditInfo"
        
        



      
  BranchDefinition:
    description: "An atomic branch record."
    type: "object"
    properties:
      X:
        type: "string"
      
  ## CName Definition ##
  CNameDefinition:
    description: "An internet cannonical name."
    type: "string"
 
  ## Service Definition ##     
  ServiceDefinition:
    description: "Is this a docker file?"
    type: "object"
    properties:
      name:
        type: "string"
        description: "Arbitrary and application unique name for the service."
      data:
        type: "object"
        description: "an object."
        
  ## TestRunner Definition ##        
  TestRunnerDefinition:
    description: "Meta information required to execute a test suite."
    type: "object"
    properties:
      name:
        type: "string"
        description: "Arbitrary and application unique name for the test runner."
      runner:
        type: "object"
        description: "Details, yet to be determined."
        
  ## Command Definition ##        
  CommandDefinition:
    description: "A (currently) OS agnostic bash shell command. Note that there is no support for token expansion in this version."
    type: "object"
    properties:
      name:
        type: "string"
        description: "A unique name or key to reference the command."
      command:
        type: "string"
        description: "The full command line to execute."
        
  ## Git Remote Definition ##        
  GitRemote:
    description: "Describes a remote reference to a Git repository."
    type: "object"
    properties:
      name:
        type: string
        description: "E.g. origin, gitlab, corpus, etc."
      uri:
        type: string

  ## Application Target Definition        
  AppTarget:
    description: "Application Targets are host environments that can run SJC applications. Since SJC applications are currently web based valid targets can be local development environments as well as cloud platforms like AWS. Future consideration may be given to hosting non web applications including native executables for mobile and desktop."
    type: "object"
    required:
    - "name"
    properties:
      audit:
        $ref: "#/definitions/AuditInfo"
      description:
        type: "string"
      endPoint:
        type: "string"
      name:
        type: "string"
      provider:
        type: "string"
      tag:
        type: "string"
  AppTemplate:
    description: "An Application Template describes an SJC standard stack plus mandatory components. Such stacks will includine LAMP, Wordpress, MEAN and Python + Django + Postgress."
    type: "object"
    required:
    - "name"
    properties:
      audit:
        $ref: "#/definitions/AuditInfo"
      description:
        type: "string"
      docker:
        type: "string"
      name:
        type: "string"
      provider:
        type: "string"
      tag:
        type: "string"
        
  AuditInfo:
    description: "The AuditInfo is becoming an SJC standard for conveying an auditable track of who made modifications when. It does not currently support the concept of 'what' was audited."
    type: "object"
    properties:
      created:
        type: "object"
        properties:
          by: 
            type: "string"
          on: 
            type: "string"
      updated:
        type: "object"
        properties:
          by: 
            type: "string"
          on: 
            type: "string"

            
  ErrorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  ErrorResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
